from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV_PATH = REPO_ROOT / ".env.dev"
DEFAULT_CONTAINER_NAME = "bunkerm-postgres"


def load_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()

    return values


def detect_container_engine() -> str:
    for candidate in ("podman", "docker"):
        if shutil.which(candidate):
            return candidate
    raise RuntimeError("Neither podman nor docker is available in PATH")


def run_sql(engine: str, container: str, password: str, user: str, database: str, sql: str) -> None:
    subprocess.run(
        [
            engine,
            "exec",
            "-e",
            f"PGPASSWORD={password}",
            container,
            "psql",
            "-U",
            user,
            "-d",
            database,
            "-v",
            "ON_ERROR_STOP=1",
            "-c",
            sql,
        ],
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Restore a PostgreSQL dump into the running Compose container.")
    parser.add_argument("backup_file", help="Path to the .dump file generated by postgres-backup.py")
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_PATH), help="Path to the env file with PostgreSQL credentials.")
    parser.add_argument("--container", default=DEFAULT_CONTAINER_NAME, help="Name of the running PostgreSQL container.")
    parser.add_argument("--target-database", required=True, help="Database name to restore into.")
    parser.add_argument("--user", help="Database user. Defaults to POSTGRES_USER from the env file.")
    parser.add_argument("--password", help="Database password. Defaults to POSTGRES_PASSWORD from the env file.")
    parser.add_argument("--drop-create", action="store_true", help="Drop and recreate the target database before restoring.")
    args = parser.parse_args()

    backup_path = Path(args.backup_file).expanduser().resolve()
    if not backup_path.exists():
        print(f"Backup file not found: {backup_path}", file=sys.stderr)
        return 1

    env_values = load_env_file(Path(args.env_file))
    database_user = args.user or env_values.get("POSTGRES_USER")
    database_password = args.password or env_values.get("POSTGRES_PASSWORD")
    if not database_user or not database_password:
        print("Missing PostgreSQL credentials. Provide --user/--password or use a valid .env.dev.", file=sys.stderr)
        return 1

    engine = detect_container_engine()
    target_database = args.target_database

    if args.drop_create:
        run_sql(engine, args.container, database_password, database_user, "postgres", f"DROP DATABASE IF EXISTS \"{target_database}\" WITH (FORCE)")

    run_sql(engine, args.container, database_password, database_user, "postgres", f"CREATE DATABASE \"{target_database}\"")

    with backup_path.open("rb") as backup_file:
        subprocess.run(
            [
                engine,
                "exec",
                "-i",
                "-e",
                f"PGPASSWORD={database_password}",
                args.container,
                "pg_restore",
                "-U",
                database_user,
                "-d",
                target_database,
                "--clean",
                "--if-exists",
                "--no-owner",
                "--no-privileges",
            ],
            stdin=backup_file,
            check=True,
        )

    print(target_database)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())